server.port=8080
spring.data.mongodb.uri=mongodb+srv://chandanak1009_db_user:Ammulu@10@cluster0.k00qwf5.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=bookstore
# JWT Configuration
bookstore.app.jwtSecret=bookstoreSecretKeyForJWTSecurityPurposesMustBeLongEnoughToBeSecure
bookstore.app.jwtExpirationMs=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandanak1009@gmail.com
spring.mail.password=zuifllockxhozmeb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.org.springframework.security=INFO
